/**
 * Common model interfaces implemented by provider adapters.
 *
 * @example
 * ```typescript
 * import type { BaseModel } from "jsr:@huuma/ai/model";
 *
 * const result = await model.generate({
 *   modelId: "gpt-4o-mini",
 *   messages: [{ role: "user", contents: "Hello!" }],
 * });
 * ```
 *
 * @module
 */
import type { Message } from "../mod.ts";
export type {
  Message,
  MessageRole,
  MessageWithRole,
  ModelMessage,
  SystemMessage,
  TextContent,
  ToolCallContent,
  ToolMessage,
  ToolResultContent,
  UserMessage,
} from "../mod.ts";
/** Common interface implemented by all model adapters. */
export interface BaseModel<T extends string = string> {
  /** Generate a complete model response.
   *
   * @param options Implementation-specific generate options (e.g. {@link OpenAIGenerateOptions}).
   */
  generate(args: unknown): Promise<ModelResult<T>>;
  /** Stream incremental model responses.
   *
   * @param options Implementation-specific stream options (e.g. {@link OpenAIGenerateOptions}).
   */
  stream(args: unknown): Promise<AsyncGenerator<ModelResult>>;
}

/** Normalized result returned by model adapters. */
export interface ModelResult<T extends string = string> {
  /** Identifier of the model that produced the result. */
  modelId: T;
  /** Messages produced by the model. */
  messages: Message[];
  /**
   * Token usage reported by the provider for this model call.
   *
   * On `generate` results the usage covers the whole call. Streams report
   * usage once the provider sends it — typically on the final chunk, which
   * may carry no messages — and the values cover the entire call, not the
   * individual chunk.
   */
  usage?: ModelUsage;
}

/** Normalized token usage of a single model call.
 *
 * Fields are only set when the provider reports them; absent fields mean
 * "not reported", not zero.
 */
export interface ModelUsage {
  /** Tokens consumed by the request input (prompt). */
  inputTokens?: number;
  /** Tokens generated by the model. */
  outputTokens?: number;
  /** Total tokens of the call as reported or derived from the other fields. */
  totalTokens?: number;
  /** Input tokens read from a provider-side prompt cache. */
  cacheReadInputTokens?: number;
  /** Input tokens written to a provider-side prompt cache. */
  cacheWriteInputTokens?: number;
  /** Output tokens spent on reasoning/thinking, when reported separately. */
  thinkingTokens?: number;
}
