/**
 * Common model interfaces implemented by provider adapters.
 *
 * @example
 * ```typescript
 * import type { BaseModel } from "jsr:@huuma/ai/model";
 *
 * const result = await model.generate({
 *   modelId: "gpt-4o-mini",
 *   messages: [{ role: "user", contents: "Hello!" }],
 * });
 * ```
 *
 * @module
 */
import type { Message } from "../mod.ts";
export { dataUrlFrom, type FileSource, fileSourceFrom } from "./file.ts";
export type {
  FileContent,
  Message,
  MessageRole,
  MessageWithRole,
  ModelMessage,
  SystemMessage,
  TextContent,
  ToolCallContent,
  ToolMessage,
  ToolResultContent,
  UserMessage,
} from "../mod.ts";
/** Common interface implemented by all model adapters. */
export interface BaseModel<T extends string = string> {
  /** Generate a complete model response.
   *
   * @param options Implementation-specific generate options (e.g. {@link OpenAIGenerateOptions}).
   */
  generate(args: unknown): Promise<ModelResult<T>>;
  /** Stream incremental model responses.
   *
   * @param options Implementation-specific stream options (e.g. {@link OpenAIGenerateOptions}).
   */
  stream(args: unknown): Promise<AsyncGenerator<ModelResult>>;
}

/** Normalized result returned by model adapters. */
export interface ModelResult<T extends string = string> {
  /** Identifier of the model that produced the result. */
  modelId: T;
  /** Messages produced by the model. */
  messages: Message[];
  /**
   * Token usage reported by the provider for this model call.
   *
   * On `generate` results the usage covers the whole call. Streams report
   * usage once the provider sends it — typically on the final chunk, which
   * may carry no messages — and the values cover the entire call, not the
   * individual chunk.
   */
  usage?: ModelUsage;
}

/** Normalized token usage of a single model call.
 *
 * Fields are only set when the provider reports them; absent fields mean
 * "not reported", not zero.
 */
export interface ModelUsage {
  /** Tokens consumed by the request input (prompt). */
  inputTokens?: number;
  /** Tokens generated by the model. */
  outputTokens?: number;
  /** Total tokens of the call as reported or derived from the other fields. */
  totalTokens?: number;
  /** Input tokens read from a provider-side prompt cache. */
  cacheReadInputTokens?: number;
  /** Input tokens written to a provider-side prompt cache. */
  cacheWriteInputTokens?: number;
  /** Output tokens spent on reasoning/thinking, when reported separately. */
  thinkingTokens?: number;
}

const MODEL_USAGE_KEYS = [
  "inputTokens",
  "outputTokens",
  "totalTokens",
  "cacheReadInputTokens",
  "cacheWriteInputTokens",
  "thinkingTokens",
] as const;

/** Sums usage reports of multiple model calls into one.
 *
 * Each field is summed across the inputs that report it; fields no input
 * reports stay absent, preserving the "absent means not reported"
 * convention of {@link ModelUsage}.
 *
 * @param usages Usage reports to sum; `undefined` entries are skipped.
 * @returns The summed usage, or `undefined` when no input carries usage.
 */
export function sumModelUsage(
  ...usages: (ModelUsage | undefined)[]
): ModelUsage | undefined {
  let result: ModelUsage | undefined;

  for (const usage of usages) {
    if (!usage) {
      continue;
    }
    for (const key of MODEL_USAGE_KEYS) {
      const value = usage[key];
      if (value !== undefined) {
        // Allocated on the first written field, so usage objects without
        // any reported field collapse to `undefined` instead of `{}`.
        result ??= {};
        result[key] = (result[key] ?? 0) + value;
      }
    }
  }

  return result;
}
